version: '3.7'
services:
  code-server:
    image: codercom/code-server
    container_name: code-server
    volumes:
      - ${project_path}:${project_path}
      - ./conf:/home/coder/.config/code-server
    ports:
      - ${outside_port}:${inside_port}
    healthcheck:
      test: curl --fail http://127.0.0.1:${inside_port} || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 5s
    restart: always
    networks:
      - code-server

networks:
  code-server:
